### ISSUE TITLE
Does not work out of the box

### ISSUE THREAD

**Issue by sergeevabc** [vimist/termtime#1]
```console
$ pip install termtime
Collecting termtime
  Downloading termtime-0.1.0.tar.gz (4.5 kB)
Installing collected packages: termtime
    Running setup.py install for termtime ... done
Successfully installed termtime-0.1.0

$ termtime
Traceback (most recent call last):
  File "C:\Python\Scripts\termtime-script.py", line 11, in <module>
    load_entry_point('termtime==0.1.0', 'console_scripts', 'termtime')()
  File "c:\python\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "c:\python\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "c:\python\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\python\lib\site-packages\termtime\__main__.py", line 7, in <module>
    import curses
  File "c:\python\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
```

**Comment by vimist** [comment]
Hey @sergeevabc, thanks for taking the time to report the bug.

Looking at the trace you posted, it looks as though you're using Windows? Unfortunately the `curses` module that `termtime` relies on isn't supported on Windows. I don't actually have a Windows machine to test on at the moment, but after a bit of searching, I came across [windows-curses](https://pypi.org/project/windows-curses), perhaps this will provide the necessary prerequisites.

Would you be able to give it a try and report back please?

**Comment by sergeevabc** [comment]
@vimist, some ```curses``` is definitely available on Windows since [termdown][1] by @trehn uses it smoothly. 

[1]:  https://github.com/trehn/termdown

**Comment by vimist** [comment]
Just had a look in their [setup.py (line 38)](https://github.com/trehn/termdown/blob/a70ac7c17b0f9e3260cdcec00725903d20e0ef7f/setup.py#L38) and it looks like it's because they are using the [windows-curses](https://pypi.org/project/windows-curses) package I mentioned.

If you can install it manually and confirm it works, I can add it as a dependency. This might resolve your other issues as well if we're lucky!

**Comment by sergeevabc** [comment]
Yes, it works with the mentioned windows-curses dependency in place, consider adding it.
